services:
  - type: web
    name: picadito-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 21
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:5173
      - key: DATABASE_URL_RAW
        fromDatabase:
          name: picadito-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: picadito-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: picadito-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: picadito-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: picadito-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: picadito-db
          property: database
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: picadito-db
    plan: free
    databaseName: picadito_db
